import type { Metadata } from "next";
import { Ruslan_Display, Nova_Round } from "next/font/google";
import "./globals.css";

const ruslanDisplay = Ruslan_Display({
	weight: "400",
});

const novaRound = Nova_Round({
	weight: "400",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body
				className={`${ruslanDisplay.className} ${novaRound.className} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
